### ISSUE TITLE
Github action to generate and upload parsed game data

### ISSUE THREAD

**Issue by hassayag** [deadlock-wiki/deadbot#64]
Automation of the game file parsing will reduce the manual work for maintaining up to date output.

Additionally, this data should be stored in a separate repo in order to keep the PRs on the `deadbot` repo cleaner. We want to migrate it to the new `deadlock-data` repo which will store a snapshot of the current patch.

**Acceptance Criteria**
Github action to run as workflow dispatch or merge to `develop` and `master` branches to do the following:
- Read decompiled game data from s3 and run the parser to generate the output data
- Upon merge, it will commit to the same branch on `deadlock-data` repo with a reference to the PR number in the commit message

**Comment by hassayag** [comment]
_Potential issue_ - investigating what a PR does is not as easy when you don't have the proof of the output data changing as you'd expect, but that can still be handled locally if you have cloned the `deadlock-data` repo

This isn't ideal, so I am going to look at potentially generating a diff as a file in the CI, letting you review changes, but without muddying the diff

**Comment by B13rg** [comment]
I think the current data should stay in this repo, and then replicated to the other.I also like having the diff to know stuff worked correctly.  I guess it depends which repo we want to be the primary source of truth.
If all the automation for updating moves to the deadlock-data repo, then it's like you said show example output as an artifact just to confirm the bot works, and move all the "production" data handling to the other repo

**Comment by B13rg** [comment]
For now I've setup https://github.com/deadlock-wiki/deadlock-data/blob/main/.github/workflows/scheduled-sync.yml to pull data over to that repo, we can see how it behaves over the next few updates.  It basically checks out the latest deadbot main branch and copies over the game data.

Since this repo is added as a submodule, it'll point directly to the repo commit that generated.
